### ISSUE TITLE
ai-issue-loop Pass 4 creates zero worktree symlinks under zsh

### ISSUE THREAD

**Issue by rtorcato** [rtorcato/repo-tooling#585]
`skills/ai-issue-loop` Pass 4 ("give it dependencies") links **nothing** when the orchestrator's shell is zsh, and fails silently. Every loop worktree on a zsh machine gets no `node_modules` at all.

## The bug

```bash
DIRS=$(jq -r '.worktree.symlinkDirectories[]? // empty' "$ROOT/.claude/settings.json" 2>/dev/null)
for d in $DIRS; do
  [ -d "$ROOT/$d" ] || continue
  ...
done
```

`for d in $DIRS` assumes **bash word-splitting on unquoted expansion**. zsh doesn't do that — `$DIRS` expands as a single word containing the embedded newline:

```
$ zsh -c 'DIRS=$(printf "a\nb\n"); n=0; for d in $DIRS; do n=$((n+1)); echo "[$d]"; done; echo "iterations: $n"'
[a
b]
iterations: 1

$ bash -c '<same>'
[a]
[b]
iterations: 2
```

So the loop runs once, `[ -d "$ROOT/node_modules⏎apps/docs/node_modules" ]` is false, `continue` fires, and no symlink is created.

## Why it's silent rather than loud

The fallback can't save it — it's gated on `$DIRS` being *empty*, and `$DIRS` is populated:

```bash
[ -z "$DIRS" ] && (cd "$WT_ROOT/$SLUG" && pnpm install)
```

So the worktree gets **neither symlinks nor an install**. Nothing checks afterwards, and the orchestrator moves straight to spawning the implementer. The agent then hits `Cannot find module` on its first `pnpm test`, which reads as the issue's fault rather than the harness's — the same misattribution #201 is cited for in that section.

Observed twice on `js-common` today (#253 → PR #254). I caught it only by asserting `[ -L "$WT/node_modules" ]` after the loop rather than trusting it.

## Fix

Iterate over lines explicitly instead of relying on splitting:

```bash
jq -r '.worktree.symlinkDirectories[]? // empty' "$ROOT/.claude/settings.json" 2>/dev/null \
| while IFS= read -r d; do
    [ -n "$d" ] || continue
    [ -d "$ROOT/$d" ] || continue
    mkdir -p "$(dirname "$WT_ROOT/$SLUG/$d")"
    ln -s "$ROOT/$d" "$WT_ROOT/$SLUG/$d"
  done
```

Verified working on zsh 5.9 / macOS.

Worth pairing with an assertion after the linking step — a `[ -L ]` check per entry, failing the pickup rather than dispatching an agent into an empty worktree. The whole failure mode here is that nothing downstream notices.

## Related

The skill already documents the *sibling* of this bug for globs in Pass 2 — *"Under zsh a glob that matches nothing aborts the whole command… `2>/dev/null` does not save you; the failure happens at expansion."* Same class, different construct; Pass 4's loop was missed.
